<Project>
	<PropertyGroup>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<RootNamespace>GitRun</RootNamespace>
		<RepositoryType>git</RepositoryType>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>
</Project>
