<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>GitRun</RootNamespace>
		<AssemblyName>GitRun</AssemblyName>

		<!-- Package -->
		<PackageId>GitRun</PackageId>
		<Version>1.0.0</Version>
		<Description>Small .NET library for running git commands and streaming their output asynchronously.</Description>
		<PackageTags>git;async;IAsyncEnumerable</PackageTags>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

</Project>
