<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>GitRun</AssemblyName>

		<PackageId>GitRun</PackageId>
		<Version>1.0.0</Version>
		<Authors>Anton Zhelezniakou</Authors>
		<Copyright>Copyright (c) 2026 Anton Zhelezniakou, WiseTech Global. All rights reserved.</Copyright>
		<Description>Small .NET library for running git commands and streaming their output asynchronously.</Description>
		<PackageTags>git</PackageTags>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes Condition="Exists('$(RepoRoot)release-notes.md')">$([System.IO.File]::ReadAllText('$(RepoRoot)release-notes.md'))</PackageReleaseNotes>

		<PackageProjectUrl>https://github.com/AntonZhelezniakou-WTG/git-run</PackageProjectUrl>
		<RepositoryUrl>https://github.com/AntonZhelezniakou-WTG/git-run</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>

		<IsAotCompatible>true</IsAotCompatible>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(RepoRoot)README.md" Pack="true" PackagePath="\" />
		<None Include="$(RepoRoot)LICENSE" Pack="true" PackagePath="\" />
		<None Include="$(RepoRoot)CHANGELOG.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
